image: node:16.14.0

pages:
  script:
  - yarn install
  - yarn build
  # The build directory is created based on the value set for projectName in
  # website/siteConfig.js. If you change it there, you need to change it here
  # as well.
  - mv ./out ./public

  artifacts:
    paths:
    - public

  only:
  - main
